name: Agent Scraper

on:
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements2.txt
      - name: Collect agent data
        run: |
          python Agent_Scraper/AgentScraper.py          
      - name: List contents of directory
        run: |
          ls Agent_Scraper/
