name: Cook County Deeds Playwright Scraper

on:
  schedule:
    - cron: '0 11 * * 1-5' # This runs the workflow every day at 6 a.m. Central Time
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python and Playwright
        uses: mheap/setup-playwright@v1
        with:
          browser: chromium
      - name: Install dependencies
        run: |
          sudo apt-get install -y libgtk-3-0 libgbm-dev libnss3 libxss1 xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper and push to Google Sheets
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          python CookCountyPlaywright/CookCountyScraperDaily.py
