name: Run ACRIS Scraper

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8 a.m. Eastern
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Playwright
        run: |
          npm install -g playwright
          playwright install
      - name: Run scraper and push to Google Sheets
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: | 
          python NYC_Acris_Scraper.py
