name: Daily Scraper

on:
  schedule:
    - cron: '0 13 * * 1-5' # This runs the workflow every day at 9 a.m. Eastern Time
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scraper and push to Google Sheets
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: |
        python Redfin_MD/Miami-Dade_Redfin.py
